<?php
$url = BASE_URL;
// print_r($this->route);
// $general=$type_venta;
//  echo "<pre>";
//  print_r($re);
// // var_dump($re);
// echo "</pre>";
 ?>
<head>
      <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
 <script type="text/javascript" src="//code.jquery.com/jquery-1.12.4.js" ></script>
 <script type="text/javascript" src="assets/js/App.js" ></script>
 <script type="text/javascript" src="assets/css/bootstrap.min.css" ></script>
 <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <!-- GOOGLE FONTS-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <title> Panaderia San Miguel </title>
    <!-- <script type="text/javascript" language="javascript" src="http://localhost:8080/Sia/sia/assets/plugins/jquery/jquery-1.9.1.min.js?ver=14702"></script> -->
	<!-- BOOTSTRAP STYLES-->
    <link href="assets/css/bootstrap.css" rel="stylesheet" />
     <!-- FONTAWESOME STYLES-->
    <link href="assets/css/font-awesome.css" rel="stylesheet" />
        <!-- CUSTOM STYLES-->
    <link href="assets/css/custom.css" rel="stylesheet" />

      <!-- #region datatables files -->
</head>
<div class="todo">
<body>
    <div id="wrapper">
      <!-- Aqui se muestra el salvapantallas -->
      <div id="panaderia" class="navbar navbar-inverse_2">
          <!-- <div class="adjust-nav_2">
              <h1>Panaderia San Miguel</h1>
          </div> -->
          <div class="adjust-nav_2 moto-widget-text-content moto-widget-text-editable">
            <p style="text-align: center;" class="moto-text_system_2">Bienvenidos al sistema</p>
            <p style="text-align: center;" class="moto-text_system_1">PANADERIA SAN MIGUEL</p>
            <p style="text-align: center;" class="moto-text_normal">
            <img src="<?php echo $url; ?>assets/img/bienvenida1.png" width="50%" style="margin-top:-3%;" alt="">
              <span class="moto-color5_5"></span>
              <br>
            </p>
          </div>
        </div>

        <!-- /. NAV TOP  -->
        <!-- Aqui finaliza el salvapantallas -->
      <div id="loco" class="">
        <!-- Aqui inicia el menu -->
        <nav class="navbar-default navbar-side col-lg-2" role="navigation">
          <div class="sidebar-collapse">
            <ul class="nav" id="main-menu">
                <li href="#sesion" >
                  <a href="<?php echo $url;?>user#page-wrapper"> Administracion </a>
                </li>
                <li class="active-link" >
                  <a id="esconder2" href="<?php echo $url;?>index#page-wrapper" > General </a>
                </li>
                <li>
                  <a id="esconder3" href="<?php echo $url;?>reposteria#page-wrapper">Pedidos de Pastel </a>
                </li>
                <?php  if ($this->session->userdata('login')){?>
               <li>
                 <a href="<?php echo $url;?>tabla#sesion"> Tabla de ventas </a>
               </li>
               <li>
                 <a href="<?php echo $url;?>detalleVenta#sesion"> Detalle de ventas Pasteleria</a>
               </li>
              <?php } ?>
                <li>
                  <form action="<?php echo $url;?>index#sesion" method="post">
                    <label for="">¿Desea cancelar o bonificar a una cuenta?</label>
                    <input class="cancel_fol" style="width:70%;" type="text" id="fol_cu" name="folio_cu" value="<?php echo isset($re->folio)?$re->folio:''?>">
                    <button class="quest btn-success" type="submit" name="button">Buscar</button>
                  </form>
                  <?php if (isset($re)&&is_object($re)) { ?>
                    <form class="" action="index#sesion" method="post">
                      <input class="hidden" type="text" name="folio_cu" value="<?php echo isset($re->folio)?$re->folio:''?>">
                      <input class="hidden" type="text" name="fecha_cu" value="<?php echo isset($re->fecha_registro)?$re->fecha_registro:''?>">
                      <label class="pe" for="">Total $<?php echo isset($re->total)?$re->total:''?></label><br>
                      <input class="hidden" type="text" id="total_cu" name="total_cu" value="<?php echo isset($re->total)?$re->total:''?>">
                      <input class="pe" id="pe_fo" type="text" name="abono" value="" placeholder="Descontar">
                      <button class="bon_can btn-success pe" disabled="disabled" type="submit" name="button">Enviar</button>
                    </form>
                  <?php } ?>
                </li>
            </ul>
          </div>
          <br><br>
          <div class="btn_num" style="font-family: Gelio, sans-serif; font-size: 2.5em;">
            <button style="height:70px;" class="col-md-4 btn-info x" type="button" name="button" data-val="1">1</button>
            <button style="height:70px;" class="col-md-4 btn-info x" type="button" name="button" data-val="2">2</button>
            <button style="height:70px;" class="col-md-4 btn-info x" type="button" name="button" data-val="3">3</button>
            <button style="height:70px;" class="col-md-4 btn-info x" type="button" name="button" data-val="4">4</button>
            <button style="height:70px;" class="col-md-4 btn-info x" type="button" name="button" data-val="5">5</button>
            <button style="height:70px;" class="col-md-4 btn-info x" type="button" name="button" data-val="6">6</button>
            <button style="height:70px;" class="col-md-4 btn-info x" type="button" name="button" data-val="7">7</button>
            <button style="height:70px;" class="col-md-4 btn-info x" type="button" name="button" data-val="8">8</button>
            <button style="height:70px;" class="col-md-4 btn-info x" type="button" name="button" data-val="9">9</button>
            <button style="height:70px;" class="col-md-4 btn-info x" type="button" name="button" data-val=".">.</button>
            <button style="height:70px;" class="col-md-4 btn-info x" type="button" name="button" data-val="0">0</button>
            <button style="height:70px;" class="col-md-4 btn-info x" type="button" name="button" data-val="-">-</button>
          </div>
        </nav>
        <!-- Aqui termina el menu -->
        <!-- /. NAV SIDE  -->
        <!-- Aqui comienza el contenido -->
        <div id="page-wrapper" class="col-lg-8" >
          <div id="page-inner"  style="background-image:url(<?php echo $url?>assets/img/fondo.png); background-size:contain;" >
            <div id="sesion" class=" row text-center pad-top">
              <?php $this->load->view($contenido); ?>
            </div>
          </div>
        </div>
        <!-- Aqui termina el contenido -->
        <form method="POST" action="<?php echo $url;?>venta/insertar_venta">
        <div style="padding: 110px 20px; text-align: center; margin-left: 13px; font-family: 'Oswald', sans-serif;" class="col-lg-2 table_total">
          <table id="totales" style="width:100%">
            <caption>Total a pagar</caption>
            <br>
            <tbody>
              <tr class="hidden">
                  <td>Uno</td>
              </tr>
            </tbody>
          </table>
          <table id="to" style="width:100%">
            <tbody>
              <hr style="border-top: 2px solid #6b6b6b;">
              <tr class="hidden">
                  <td>Uno</td>
              </tr>
            </tbody>
          </table>
          <br>
          <button type="button" class="venta btn btn-danger disabled" name="button">Terminar venta</button>
          <br><br>
            <div id="imprimir">

            </div>
        </div>
      </form>
    </div>
  </div>


     <!-- /. WRAPPER  -->
    <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
      <!-- BOOTSTRAP SCRIPTS -->
    <script src="assets/js/bootstrap.min.js"></script>
      <!-- CUSTOM SCRIPTS -->
    <script src="assets/js/custom.js"></script>


</body>
</div>
<script type="text/javascript">
var total_blanco = 0;
var total_dulce = 0;
var total_repos = 0;
var total_velas = 0;
var total_leche = 0;
var total_cafe = 0;
var total_choco = 0;
var total_rebanadas = 0;
var total_gelatinas = 0;
var total_pasteles = 0;
var total_varios = 0;

  $("#blanco").click(function(event){
    $(".unidades").removeClass("hidden");
    $(".enviar").removeClass("hidden");
  });

  var total1 = 0;
  $('.bolillo').change(function(){
    total1 = resultado();
    document.getElementById("capa").innerHTML = 'El total de pan blanco es: $'+total1+'';
    // console.log("dentro del trigger del change");
  });
  function resultado(){
    total_blanco=0;
    $(".bolillo").each(function(e){
      var i = $(this).attr("data-precio");
      var cantidad = $(this).val();
      total_blanco+= cantidad * i;
    });
    return total_blanco;
  }
  $(".enviar").click(function(event){
    $("#1").remove();
    if (total1==0){
    }else{
      $('#totales tr:last').after('<tr id=1><td>Pan Blanco</td><td>$</td><td id="a">'+total1+'</td></tr>');
      $(".venta").removeClass("disabled");
      $(".delete").removeClass("hidden");
      // $(".enviar").addClass("disabled");
      $("#total_gen").remove();
      $("#ticket").remove();
      $("#ticket_imprimir").remove();
    }

  });

  // $(".delete").click(function (event) {
  //    total = 0;
  //     $(".delete").addClass("hidden");
  //     $("#blanco_precio").remove();
  //     $("#1").remove();
  //     $(".enviar").removeClass("disabled");
  //     $(".venta").addClass("disabled");
  //     $("#total_gen").remove();
  //     $("#ticket").remove();
  //     $("#ticket_imprimir").remove();
  // });

  $("#dulce").click(function(event){
    $(".precios").removeClass("hidden");
    $(".enviar2").removeClass("hidden");
  });
  var total2 = 0;
  $('.dulce').change(function(){
    total2 = resultado2();
    document.getElementById("capa2").innerHTML = 'El total de pan dulce es: $'+total2+'';
  });
  function resultado2(){
    total_dulce=0;
    $(".dulce").each(function(e){
      var i = $(this).attr("data-precio");
      var cantidad = $(this).val();
      total_dulce+= cantidad * i ;
      // console.log(total_blanco);
    });
    return total_dulce;
  }

  $(".enviar2").click(function(event){
    $("#2").remove();
    if (total2==0) {
    }else{
      $('#totales tr:last').after('<tr id=2><td>Pan Dulce</td><td>$</td><td id="b">'+total2+'</td></tr>');
      $(".venta").removeClass("disabled");
      $(".delete2").removeClass("hidden");
      // $(".enviar2").addClass("disabled");
      $("#total_gen").remove();
      $("#ticket").remove();
      $("#ticket_imprimir").remove();
    }
  });

  // $(".delete2").click(function (event) {
  //   total_dulce = 0;
  //   $(".delete2").addClass("hidden");
  //   $("#dulce_precio").remove();
  //   $("#2").remove();
  //   $(".enviar2").removeClass("disabled");
  //   $(".venta").addClass("disabled");
  //   $("#total_gen").remove();
  //   $("#ticket").remove();
  //   $("#ticket_imprimir").remove();
  // });

  $("#repos").click(function(event){
    $(".rebanadas").removeClass("hidden");
    $(".enviar3").removeClass("hidden");
  });
  var total3 = 0;
  $('.reposteria').change(function(){
    total3 = resultado3();
    document.getElementById("capa3").innerHTML = 'El total de reposteria es: $'+total3+'';
  });
  function resultado3(){
    total_repos=0;
    $(".reposteria").each(function(e){
      var i = $(this).attr("data-precio");
      var cantidad = $(this).val();
      total_repos+= cantidad * i ;
      // console.log(tota);
    });
    return total_repos;
  }

  $(".enviar3").click(function(event){
    $("#3").remove();
    if (total3==0) {
    }else{
      $('#totales tr:last').after('<tr id=3><td>Reposteria</td><td>$</td><td id="c">'+total3+'</td></tr>');
      $(".venta").removeClass("disabled");
      $(".delete3").removeClass("hidden");
      // $(".enviar3").addClass("disabled");
      $("#total_gen").remove();
      $("#ticket").remove();
      $("#ticket_imprimir").remove();
    }
  });
  //
  // $(".delete3").click(function (event) {
  //   total_repos = 0;
  //   $(".delete3").addClass("hidden");
  //   $("#repost").remove();
  //   $("#3").remove();
  //   $(".enviar3").removeClass("disabled");
  //   $(".venta").addClass("disabled");
  //   $("#total_gen").remove();
  //   $("#ticket").remove();
  //   $("#ticket_imprimir").remove();
  // });

  $("#velas").click(function(event){
    $(".velas").removeClass("hidden");
    $(".enviar4").removeClass("hidden");
  });

  var total4 = 0;
  $('.velas').change(function(){
    total4 = resultado4();
    document.getElementById("capa4").innerHTML = 'El total de velas es: $'+total4+'';
  });
  function resultado4(){
    total_velas=0;
    $(".velas").each(function(e){
      var i = $(this).attr("data-precio");
      var cantidad = $(this).val();
      total_velas+= cantidad * i ;
      // console.log(tota);
    });
    return total_velas;
  }


  $(".enviar4").click(function(event){
    $("#4").remove();
    if (total4==0) {
    }else {
      $('#totales tr:last').after('<tr id=4><td>Velas</td><td>$</td><td id="d">'+total4+'</td></tr>');
      $(".venta").removeClass("disabled");
      $(".delete4").removeClass("hidden");
      // $(".enviar4").addClass("disabled");
      $("#total_gen").remove();
      $("#ticket").remove();
      $("#ticket_imprimir").remove();
    }
  });

  $(".delete4").click(function (event) {
    total_velas = 0;
    $(".delete4").addClass("hidden");
    $("#velast").remove();
    $("#4").remove();
    $(".enviar4").removeClass("disabled");
    $(".venta").addClass("disabled");
    $("#total_gen").remove();
    $("#ticket").remove();
    $("#ticket_imprimir").remove();
  });

  $("#varios").click(function(event){
    $(".varios").removeClass("hidden");
    $(".enviar5").removeClass("hidden");
    $(".enviar6").removeClass("hidden");
    $(".enviar7").removeClass("hidden");
  });

  // $(".enviar5").click(function(event){
  //   $(".leche").each(function(e){
  //     var i = $(this).attr("data-precio");
  //     var cantidad = $(this).val();
  //     total_leche+= cantidad * i ;
  //     // console.log(total_blanco);
  //   });
  //   var capa = document.getElementById("capa5");
  //   var h3 = document.createElement("h3");
  //   h3.id="lechet"
  //   h3.innerHTML = 'El total de leche es: $'+total_leche+'';
  //   capa.appendChild(h3);
  //
  //   $('#totales tr:last').after('<tr id=5><td>Leche</td><td>$</td><td id="e">'+total_leche+'</td></tr>');
  //   $(".venta").removeClass("disabled");
  //   $(".delete5").removeClass("hidden");
  //   $(".enviar5").addClass("disabled");
  //   $("#total_gen").remove();
  //   $("#ticket").remove();
  //   $("#ticket_imprimir").remove();
  // });
  //
  // $(".delete5").click(function (event) {
  //   total_leche = 0;
  //   $(".delete5").addClass("hidden");
  //   $("#lechet").remove();
  //   $("#5").remove();
  //   $(".enviar5").removeClass("disabled");
  //   $(".venta").addClass("disabled");
  //   $("#total_gen").remove();
  //   $("#ticket").remove();
  //   $("#ticket_imprimir").remove();
  // });

  $('.cafe').change(function(){
    total6 = resultado6();
    document.getElementById("capa6").innerHTML = 'El total de cafe es: $'+total6+'';
  });
  function resultado6(){
    total_cafe=0;
    $(".cafe").each(function(e){
      var i = $(this).attr("data-precio");
      var cantidad = $(this).val();
      total_cafe+= cantidad * i ;
      // console.log(tota);
    });
    return total_cafe;
  }

  $(".enviar6").click(function(event){
    $("#6").remove();
    if (total6==0) {
    }else{
    $('#totales tr:last').after('<tr id=6><td>Cafe</td><td>$</td><td id="f">'+total_cafe+'</td></tr>');
    $(".venta").removeClass("disabled");
    $(".delete6").removeClass("hidden");
    // $(".enviar6").addClass("disabled");
    $("#total_gen").remove();
    $("#ticket").remove();
    $("#ticket_imprimir").remove();
  }
  });

  $(".delete6").click(function (event) {
    total_cafe = 0;
    $(".delete6").addClass("hidden");
    $("#cafet").remove();
    $("#6").remove();
    $(".enviar6").removeClass("disabled");
    $(".venta").addClass("disabled");
    $("#total_gen").remove();
    $("#ticket").remove();
    $("#ticket_imprimir").remove();
  });

  $('.choco').change(function(){
    total7 = resultado7();
    document.getElementById("capa7").innerHTML = 'El total de Chocolate es: $'+total7+'';
  });

  function resultado7(){
    total_choco=0;
    $(".choco").each(function(e){
      var i = $(this).attr("data-precio");
      var cantidad = $(this).val();
      total_choco+= cantidad * i ;
      // console.log(total_blanco);
    });
    return total_choco;
  }

  $(".enviar7").click(function(event){
    $("#7").remove();
      if (total7==0) {
    }else{
      $('#totales tr:last').after('<tr id=7><td>Chocolate</td><td>$</td><td id="g">'+total_choco+'</td></tr>');
      $(".venta").removeClass("disabled");
      $(".delete7").removeClass("hidden");
      // $(".enviar7").addClass("disabled");
      $("#total_gen").remove();
      $("#ticket").remove();
      $("#ticket_imprimir").remove();
    }
  });

  $(".delete7").click(function (event) {
    total_choco = 0;
    $(".delete7").addClass("hidden");
    $("#chocot").remove();
    $("#7").remove();
    $(".enviar7").removeClass("disabled");
    $(".venta").addClass("disabled");
    $("#total_gen").remove();
    $("#ticket").remove();
    $("#ticket_imprimir").remove();
  });

  $("#rebanadass").click(function(event){
    $(".repos").removeClass("hidden");
    $(".enviar8").removeClass("hidden");
    $(".enviar9").removeClass("hidden");
    $(".enviar10").removeClass("hidden");
    $(".enviar11").removeClass("hidden");
  });

  $('.reban').change(function(){
    total8 = resultado8();
    document.getElementById("capa8").innerHTML = 'El total de Rebanadas es: $'+total8+'';
  });

  function resultado8(){
    total_rebanadas=0;
    $(".reban").each(function(e){
      var i = $(this).attr("data-precio");
      var cantidad = $(this).val();
      total_rebanadas+= cantidad * i ;
      // console.log(total_blanco);
    });
    return total_rebanadas;
  }

  $(".enviar8").click(function(event){
      $("#8").remove();
    if (total8==0) {
    }else {
      $('#totales tr:last').after('<tr id=8><td>Rebanadas</td><td>$</td><td id="h">'+total_rebanadas+'</td></tr>');
      $(".venta").removeClass("disabled");
      $(".delete8").removeClass("hidden");
      // $(".enviar8").addClass("disabled");
      $("#total_gen").remove();
      $("#ticket").remove();
      $("#ticket_imprimir").remove();
    }
  });

  $(".delete8").click(function (event) {
    total_rebanadas = 0;
    $(".delete8").addClass("hidden");
    $("#rebanadast").remove();
    $("#8").remove();
    $(".enviar8").removeClass("disabled");
    $(".venta").addClass("disabled");
    $("#total_gen").remove();
    $("#ticket").remove();
    $("#ticket_imprimir").remove();
  });

  $("#gelatinass").click(function(event){
    $(".repos").removeClass("hidden");
    $(".enviar9").removeClass("hidden");
  });

  $('.gelat').change(function(){
    total9 = resultado9();
    document.getElementById("capa9").innerHTML = 'El total de Rebanadas es: $'+total9+'';
  });

  function resultado9(){
    total_gelatinas=0;
    $(".gelat").each(function(e){
      var i = $(this).attr("data-precio");
      var cantidad = $(this).val();
      total_gelatinas+= cantidad * i ;
      // console.log(total_blanco);
    });
    return total_gelatinas;
  }

  $(".enviar9").click(function(event){
    $("#9").remove();
      if (total9==0) {
    }else {
      $('#totales tr:last').after('<tr id=9><td>Gelatinas</td><td>$</td><td id="i">'+total_gelatinas+'</td></tr>');
      $(".venta").removeClass("disabled");
      $(".delete9").removeClass("hidden");
      // $(".enviar9").addClass("disabled");
      $("#total_gen").remove();
      $("#ticket").remove();
      $("#ticket_imprimir").remove();
    }
  });

  $(".delete9").click(function (event) {
    total_gelatinas = 0;
    $(".delete9").addClass("hidden");
    $("#gelatinast").remove();
    $("#9").remove();
    $(".enviar9").removeClass("disabled");
    $(".venta").addClass("disabled");
    $("#total_gen").remove();
    $("#ticket").remove();
    $("#ticket_imprimir").remove();
  });

  $("#pasteless").click(function(event){
    $(".repos").removeClass("hidden");
    $(".enviar10").removeClass("hidden");
  });

  $('.pastel').change(function(){
    total10 = resultado10();
    document.getElementById("capa10").innerHTML = 'El total de Rebanadas es: $'+total10+'';
  });

  function resultado10(){
    total_pasteles=0;
    $(".pastel").each(function(e){
      var i = $(this).attr("data-precio");
      var cantidad = $(this).val();
      total_pasteles+= cantidad * i ;
      // console.log(total_blanco);
    });
    return total_pasteles;
  }

  $(".enviar10").click(function(event){
    $("#10").remove();
      if (total10==0) {
    }else {
      $('#totales tr:last').after('<tr id=10><td>Pasteles</td><td>$</td><td id="j">'+total_pasteles+'</td></tr>');
      $(".venta").removeClass("disabled");
      $(".delete10").removeClass("hidden");
//      $(".enviar10").addClass("disabled");
      $("#total_gen").remove();
      $("#ticket").remove();
      $("#ticket_imprimir").remove();
    }
  });

  $(".delete10").click(function (event) {
    total_pasteles = 0;
    $(".delete10").addClass("hidden");
    $("#pastelest").remove();
    $("#10").remove();
    //$(".enviar10").removeClass("disabled");
    $(".venta").addClass("disabled");
    $("#total_gen").remove();
    $("#ticket").remove();
    $("#ticket_imprimir").remove();
  });

  $("#varios2s").click(function(event){
    $(".repos").removeClass("hidden");
    $(".enviar11").removeClass("hidden");
  });
  $('.varios').change(function(){
    total11 = resultado11();
    document.getElementById("capa11").innerHTML = 'El total de Varios es: $'+total11+'';
  });

  function resultado11(){
    total_varios=0;
    $(".varios").each(function(e){
      var i = $(this).attr("data-precio");
      var cantidad = $(this).val();
      if (i==undefined) {
        i=0;
        // console.log("cantidad: "+cantidad+" y precio: "+i );
      }else{
        total_varios+= cantidad * i ;
        // console.log("cantidad: "+cantidad+" y precio: "+i );
      }
    });
    return total_varios;
  }


  $(".enviar11").click(function(event){
    $("#11").remove();
      if (total11==0) {
    }else {
      $('#totales tr:last').after('<tr id=11><td>Varios</td><td>$</td><td id="k">'+total11+'</td></tr>');
      $(".venta").removeClass("disabled");
      $(".delete11").removeClass("hidden");
      // $(".enviar11").addClass("disabled");
      $("#total_gen").remove();
      $("#ticket").remove();
      $("#ticket_imprimir").remove();
    }
  });

  $(".delete11").click(function (event) {
    total_varios = 0;
    $(".delete11").addClass("hidden");
    $("#variost").remove();
    $("#11").remove();
    $(".enviar11").removeClass("disabled");
    $(".venta").addClass("disabled");
    $("#total_gen").remove();
    $("#ticket").remove();
    $("#ticket_imprimir").remove();
  });


  $(".venta").click(function(event){
    var a = $("#a").text() != "" ? parseFloat($("#a").text()):0;
    var b = $("#b").text() != "" ? parseInt($("#b").text()):0;
    var c = $("#c").text() != "" ? parseInt($("#c").text()):0;
    var d = $("#d").text() != "" ? parseInt($("#d").text()):0;
    var e = $("#e").text() != "" ? parseFloat($("#e").text()):0;
    var f = $("#f").text() != "" ? parseFloat($("#f").text()):0;
    var g = $("#g").text() != "" ? parseFloat($("#g").text()):0;
    var h = $("#h").text() != "" ? parseFloat($("#h").text()):0;
    var i = $("#i").text() != "" ? parseFloat($("#i").text()):0;
    var j = $("#j").text() != "" ? parseFloat($("#j").text()):0;
    var k = $("#k").text() != "" ? parseFloat($("#k").text()):0;
    var can = $("#can").text() != "" ? parseFloat($("#can").text()):0;
    var pre = $("#pre").text() != "" ? parseFloat($("#pre").text()):0;
    var nom = $("#nom").text() != "" ? $("#nom").text():0;
    var dir = $("#dir").text() != "" ? $("#dir").text():0;
    var corr = $("#corr").text() != "" ? $("#corr").text():0;
    var espe = $("#espe").text() != "" ? $("#espe").text():0;
    var base = $("#bas").text() != "" ? $("#bas").text():0;
    var anticipo = $("#ant").text() != "" ? $("#ant").text():0;
    var rell = $("#rell").text() != "" ? $("#rell").text():0;
    var cel = $("#cel").text() != "" ? $("#cel").text():0;
    var num = $("#num").text() != "" ? $("#num").text():0;
    console.log('base: ',base);
    if (can && pre && nom && dir && rell && num && espe && corr && cel && base) {
      var gen = parseInt(parseInt(can * pre) + parseInt(base)) - parseInt(anticipo);
      // console.log('total:',gen);
      // console.log('total y base', parseInt(gen) + parseInt(base));
      $('#to tr:last').after('<tr id="total_gen"><td>El total de pasteleria</td><td>$</td><td style="text-align:center;">'+gen+'<input class="hidden" type="text" name="total_venta_paste" value="'+gen+'"></td></tr>');
      $('#to tr:last').after('<input class="hidden" type="text" name="total_venta_nom" value="'+nom+'">');
      $('#to tr:last').after('<input class="hidden" type="text" name="total_venta_dir" value="'+dir+'">');
      $('#to tr:last').after('<input class="hidden" type="text" name="total_venta_espe2" value="'+espe+'">');
      $('#to tr:last').after('<input class="hidden" type="text" name="total_venta_correo2" value="'+corr+'">');
      $('#to tr:last').after('<input class="hidden" type="text" name="total_venta_relle" value="'+rell+'">');
      $('#to tr:last').after('<input class="hidden" type="text" name="total_venta_base" value="'+base+'">');
      $('#to tr:last').after('<input class="hidden" type="text" name="total_venta_anti" value="'+anticipo+'">');
      $('#to tr:last').after('<input class="hidden" type="text" name="total_venta_num" value="'+num+'">');
      $('#to tr:last').after('<input class="hidden" type="text" name="total_venta_cel" value="'+cel+'">');
      $('#to tr:last').after('<input class="hidden" type="text" name="total_venta_can" value="'+can+'">');
    }else{
      var gen = a + b + c + d + e + f + g + h + i + j + k;
      $('#to tr:last').after('<tr id="total_gen"><td>El total es</td><td>$</td><td style="text-align:center;">'+gen+'<input class="hidden" type="text" name="total_venta" value="'+gen+'"></td></tr>');
    }

    $(".venta").addClass("disabled");
    var imprimir = document.getElementById("imprimir");
    var ticket = document.createElement("button");
    ticket.id="ticket_imprimir";
    ticket.name="submit";
    ticket.type="submit";
    ticket.className="btn btn-success";
    ticket.innerHTML = 'Imprimir ticket';
    imprimir.appendChild(ticket);
  });

  $("#imprimir").click(function(event){
    var hola = confirm("¿Desea finalizar la venta e imprimir el ticket de compra?");
    // console.log(hola);
  });

  $(".bon_can").click(function(event){
    var hola = confirm("¿Desea bonificar o cancelar la cuenta e imprimir otro ticket?");
    $('.pe').hide();
  });

  // $(".quest").click(function(){
  //   // $(".pe").removeClass("hidden");
  // });

$("#esconder1").click(function(){
   $('#panaderia').addClass("hidden");
   $('#loco').removeClass("hidden");

});

$("#pe_fo").change(function(){
  var t = $(this).val();
  var g = $("#total_cu").val();
  if (t<=g) {
     $('.pe').removeAttr("disabled");
  }else{
    alert("No puede devolver una cantidad mayor al total")
    $('.pe').attr("disabled","disabled");
  }
});

 //
  //$(document).ready(function(){
 //  $("body").keyup(function (e) {
    // if (e.keyCode == 66) {
    //   if ($("#loco").hasClass("hidden")) {
    //     $('#panaderia').addClass("hidden");
    //     $('#loco').removeClass("hidden");
    //   }else{
    //     $('#panaderia').removeClass("hidden");
    //     $('#loco').addClass("hidden");
    //   }
    // }

   //});
 // });



</script>
