<?php
$url = BASE_URL;
// echo "<pre>";
// print_r($result);
// echo "</pre>";
// $general = $type_venta;
 ?>
 <style media="screen">
     .modal-body>table {
        border-collapse: collapse;
        width: 100%;
    }
    th, td {
        padding: 8px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }
    tr:hover {
      background-color:#dbdbdb;
    }
 </style>
   <h1>Tabla del detalle de ventas de Pasteleria</h1>
<br>
<div class="col-md-12">
  <br><br>
  <table class="table table-striped table-bordered table-list" id="tabla">
    <thead>
        <tr>
            <th>#</th>
            <th>Tipo de Venta</th>
            <th>Nombre del cliente</th>
            <th>Dirección</th>
            <th>Telefono</th>
            <th>Correo</th>
            <th>Especificaciones</th>
            <th>Tipo de relleno</th>
            <th>Cantidad Kg</th>
            <th>Base</th>
            <th>Anticipo</th>
            <th>Total</th>
            <th>Detalle</th>
        </tr>
    </thead>
    <tbody>
      <?php if ($result) { ?>
        <?php foreach ($result as $key => $value) {
          // print_r($result);
          ?>
          <tr>
            <td><?php echo $value->idventas_pasteles ?></td>
            <td><?php echo str_replace("_"," ",$value->tipo_venta); ?></td>
            <td><?php echo substr($value->nombre,0,6)?></td>
            <td><?php echo substr($value->direccion,0,6)?></td>
            <td><?php echo $value->telefono?></td>
            <td><?php echo $value->correo!=''?$value->correo:'Sin datoss';?></td>
            <td><?php echo $value->especificaciones!=''?$value->especificaciones:'Sin datos'?></td>
            <td><?php echo $value->relleno?></td>
            <td><?php echo $value->cantidad?></td>
            <td><?php echo $value->base!=0?"$".$value->base:'Sin base'?></td>
            <td><?php echo $value->anticipo!=0?"$".$value->anticipo:'Sin anticipo'?></td>
            <td><?php echo "$".$value->total?></td>
            <!-- <form action="<?php echo $url;?>#sesion" method="post"> -->
            <td><button class="btn btn-success detalles" data-toggle="modal" data-target="#<?php echo $value->idventas_pasteles?>" >Detalle</button></td>
            <!-- </form> -->
          </tr>
        <?php } ?>
      <?php }else{ ?>
      <?php } ?>
    </tbody>
  </table>
  <?php if ($result) { ?>
    <?php foreach ($result as $ke => $valu) { ?>
      <div class="modal fade" id="<?php echo $valu->idventas_pasteles?>" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <h3 class="modal-title" id="exampleModalLabel">Detalles de la Venta</h3>
            </div>
            <div class="modal-body">
              <table>
                <tr>
                  <td>Nombre:</td>
                  <td><?php echo $valu->nombre ?></td>
                </tr>
                <tr>
                  <td>Dirección:</td>
                  <td><?php echo $valu->direccion ?></td>
                </tr>
                <tr>
                  <td>Telefono:</td>
                  <td><?php echo $valu->telefono ?></td>
                </tr>
                <tr>
                  <td>Correo:</td>
                  <td><?php echo $valu->correo==''?$valu->correo:'Sin datos';?></td>
                </tr>
                <tr>
                  <td>Especificaciones:</td>
                  <td><?php echo $valu->especificaciones ?></td>
                </tr>
                <tr>
                  <td>Tipo de relleno:</td>
                  <td><?php echo $valu->relleno ?></td>
                </tr>
                <tr>
                  <td>Cantidad:</td>
                  <td><?php echo $valu->cantidad ?></td>
                </tr>
                <tr>
                  <td>Base:</td>
                  <td><?php echo $valu->base!=''?"$".$valu->base:'Sin base'; ?></td>
                </tr>
                <tr>
                  <td>Anticipo:</td>
                  <td><?php echo $valu->anticipo!=''?"$".$valu->anticipo:'Sin anticipo'; ?></td>
                </tr>
                <tr>
                  <td>Total:</td>
                  <td><?php echo "$".$valu->total ?></td>
                </tr>
              </table>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
              <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
            </div>
          </div>
        </div>
      </div>
    <?php } ?>
  <?php } ?>

  <div class="col-md-2">
    <form action="<?php echo $url;?>excel_export/action/<?php echo $general ?>" method="post">
      <button class="btn btn-success btn-lg m-r-5" type="submit" name="export"><i class="fa fa-file-excel-o "></i> Generar excel</button>
      <input class="hidden" type="text" name="type_venta2" value="Pedidos_pasteles">&nbsp;
    </form>
  </div>
  <div class="col-md-2">
    <form action="<?php echo $url;?>pdfs/generar/<?php echo $general ?>" method="post">
      <button class="btn btn-danger btn-lg m-r-5" type="submit" name="export" target="_blank"><i class="fa fa-file-pdf-o "></i> Generar imprimir</button>
        <input class="hidden" type="text" name="type_venta2" value="Pedidos_pasteles">&nbsp;
      <!-- <input type="submit" value="Crear PDF" title="Crear PDF" /> -->
    </form>
  </div>
</div>

<script type="text/javascript">
$(document).ready(function() {
      //  $('#tabla').dataTable( );
     $('#tabla').DataTable( {

              "ordering": true,
              "language": {
                    "zeroRecords": "No se encontró el registro",
                    "info": "Página _PAGE_ de _PAGES_",
                    "search": "Buscar: ",
                    "lengthMenu": 'Mostrar _MENU_  registros',
                    "infoFiltered": "(Encontrados de _MAX_ registros)",
                        "paginate":{
                          "previous": "Anterior",
                          "next": "Siguiente"
                        }
              }
            }  );

    } );
$('.detalles').on('click', function(){
  var id = $(this).attr('data-id');

});
</script>
